"""Add spayed_neutered and vaccinated to Pet

Revision ID: a74b8f7f2ac9
Revises: 9bc51c18b82e
Create Date: 2026-05-20 04:50:27.905004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a74b8f7f2ac9'
down_revision = '9bc51c18b82e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spayed_neutered', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('vaccinated', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_column('vaccinated')
        batch_op.drop_column('spayed_neutered')

    # ### end Alembic commands ###
