"""Add pet files and rename status

Revision ID: f684a9d08de5
Revises: eacd031b0e3b
Create Date: 2026-05-18 00:02:37.895609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f684a9d08de5'
down_revision = 'eacd031b0e3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pet_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('owner_valid_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('medical_record_file', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.drop_column('adoption_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adoption_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('status')
        batch_op.drop_column('medical_record_file')
        batch_op.drop_column('owner_valid_id')
        batch_op.drop_column('pet_image')

    # ### end Alembic commands ###
